-- A707 initial schema for the currently implemented Backend and Yjs services.
-- Flyway executes this migration against an empty PostgreSQL database.
-- This migration is intentionally non-destructive: it contains no DROP, TRUNCATE, or DML.

CREATE TABLE public.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR NULL,
    user_profile_image VARCHAR NULL,
    email VARCHAR NOT NULL,
    phone VARCHAR NULL,
    job_family VARCHAR NULL,
    job_role VARCHAR NULL,
    user_description TEXT NULL,
    sex VARCHAR NULL,
    age INTEGER NULL,
    user_color VARCHAR NOT NULL DEFAULT '#000000',
    space_order TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT ck_users_nickname_length CHECK (char_length(nickname) <= 20),
    CONSTRAINT ck_users_sex CHECK (sex IN ('M', 'F')),
    CONSTRAINT ck_users_age CHECK (age IN (10, 20, 30, 40, 50, 60))
);

CREATE TABLE public.teams (
    team_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    team_name VARCHAR NOT NULL,
    team_description TEXT NULL,
    team_owner_id BIGINT NOT NULL,
    team_profile_image VARCHAR NULL,
    team_color VARCHAR NOT NULL DEFAULT '#000000',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    team_invite_link VARCHAR NULL,
    CONSTRAINT pk_teams PRIMARY KEY (team_id)
);

CREATE TABLE public.team_roles (
    team_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    team_id BIGINT NOT NULL,
    role_name VARCHAR NOT NULL,
    color VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_team_roles PRIMARY KEY (team_role_id),
    CONSTRAINT uk_team_roles_team_name UNIQUE (team_id, role_name)
);

CREATE TABLE public.members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    authority VARCHAR NOT NULL,
    team_role_id BIGINT NULL,
    nickname VARCHAR NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (member_id),
    CONSTRAINT uk_members_team_user UNIQUE (team_id, user_id)
);

CREATE TABLE public.invitations (
    invitation_id UUID,
    team_id BIGINT NOT NULL,
    inviter_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_invitations PRIMARY KEY (invitation_id),
    CONSTRAINT uk_invitations_team_target UNIQUE (team_id, target_user_id)
);

CREATE TABLE public.meeting_rooms (
    meeting_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    team_id BIGINT NOT NULL,
    host_id BIGINT NOT NULL,
    meeting_room_name VARCHAR(250) NOT NULL DEFAULT '새 회의',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_meeting_rooms PRIMARY KEY (meeting_room_id)
);

CREATE TABLE public.participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    meeting_room_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    participants_role VARCHAR(50) NULL,
    is_in_meeting BOOLEAN NOT NULL,
    CONSTRAINT pk_participants PRIMARY KEY (participant_id),
    CONSTRAINT uk_participants_room_member UNIQUE (meeting_room_id, member_id)
);

CREATE TABLE public.documents (
    document_id UUID NOT NULL,
    team_id BIGINT NOT NULL,
    document_title VARCHAR(1000) NOT NULL DEFAULT '새 문서',
    final_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_documents PRIMARY KEY (document_id),
    CONSTRAINT ck_documents_final_version CHECK (final_version >= 0)
);

CREATE TABLE public.documents_state (
    document_id UUID NOT NULL,
    yjs_state BYTEA NOT NULL,
    binary_size INTEGER NOT NULL,
    state_hash BYTEA NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    persisted_revision BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_documents_state PRIMARY KEY (document_id),
    CONSTRAINT ck_documents_state_hash_length CHECK (octet_length(state_hash) = 32),
    CONSTRAINT ck_documents_state_binary_size CHECK (binary_size = octet_length(yjs_state)),
    CONSTRAINT ck_documents_state_schema_version CHECK (schema_version > 0),
    CONSTRAINT ck_documents_state_persisted_revision CHECK (persisted_revision >= 0)
);

CREATE TABLE public.documents_version (
    document_version_id UUID NOT NULL,
    document_id UUID NOT NULL,
    version_number INTEGER NOT NULL,
    title_snapshot VARCHAR(1000) NOT NULL DEFAULT '새 문서',
    yjs_state BYTEA NOT NULL,
    editor_json JSONB NOT NULL,
    trigger_type VARCHAR(30) NOT NULL,
    binary_size INTEGER NOT NULL,
    state_hash BYTEA NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    source_version_id UUID NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id UUID NULL,
    CONSTRAINT pk_documents_version PRIMARY KEY (document_version_id),
    CONSTRAINT uk_documents_version_number UNIQUE (document_id, version_number),
    CONSTRAINT uk_documents_version_request UNIQUE (document_id, request_id),
    CONSTRAINT ck_documents_version_hash_length CHECK (octet_length(state_hash) = 32),
    CONSTRAINT ck_documents_version_number CHECK (version_number > 0),
    CONSTRAINT ck_documents_version_binary_size CHECK (binary_size = octet_length(yjs_state)),
    CONSTRAINT ck_documents_version_schema_version CHECK (schema_version > 0)
);

ALTER TABLE public.members
    ADD CONSTRAINT fk_users_to_members_1
    FOREIGN KEY (user_id) REFERENCES public.users (user_id)
    ON DELETE RESTRICT;

ALTER TABLE public.members
    ADD CONSTRAINT fk_teams_to_members_1
    FOREIGN KEY (team_id) REFERENCES public.teams (team_id)
    ON DELETE RESTRICT;

ALTER TABLE public.members
    ADD CONSTRAINT fk_team_roles_to_members_1
    FOREIGN KEY (team_role_id) REFERENCES public.team_roles (team_role_id)
    ON DELETE SET NULL;

ALTER TABLE public.team_roles
    ADD CONSTRAINT fk_teams_to_team_roles_1
    FOREIGN KEY (team_id) REFERENCES public.teams (team_id)
    ON DELETE RESTRICT;

ALTER TABLE public.documents
    ADD CONSTRAINT fk_teams_to_documents_1
    FOREIGN KEY (team_id) REFERENCES public.teams (team_id)
    ON DELETE RESTRICT;

ALTER TABLE public.meeting_rooms
    ADD CONSTRAINT fk_teams_to_meeting_rooms_1
    FOREIGN KEY (team_id) REFERENCES public.teams (team_id)
    ON DELETE RESTRICT;

ALTER TABLE public.participants
    ADD CONSTRAINT fk_meeting_rooms_to_participants_1
    FOREIGN KEY (meeting_room_id) REFERENCES public.meeting_rooms (meeting_room_id)
    ON DELETE CASCADE;

ALTER TABLE public.participants
    ADD CONSTRAINT fk_members_to_participants_1
    FOREIGN KEY (member_id) REFERENCES public.members (member_id)
    ON DELETE CASCADE;

ALTER TABLE public.documents_state
    ADD CONSTRAINT fk_documents_to_documents_state_1
    FOREIGN KEY (document_id) REFERENCES public.documents (document_id)
    ON DELETE CASCADE;

ALTER TABLE public.documents_version
    ADD CONSTRAINT fk_documents_to_documents_version_1
    FOREIGN KEY (document_id) REFERENCES public.documents (document_id)
    ON DELETE CASCADE;

ALTER TABLE public.documents_version
    ADD CONSTRAINT fk_documents_version_source
    FOREIGN KEY (source_version_id) REFERENCES public.documents_version (document_version_id)
    ON DELETE SET NULL;

CREATE UNIQUE INDEX uk_users_email_active
    ON public.users (email)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_members_user_id
    ON public.members (user_id);

CREATE INDEX idx_team_roles_team_id
    ON public.team_roles (team_id);

CREATE INDEX idx_members_team_role_id
    ON public.members (team_role_id);

CREATE INDEX idx_documents_team_id
    ON public.documents (team_id);

CREATE INDEX idx_meeting_rooms_team_id
    ON public.meeting_rooms (team_id);

CREATE INDEX idx_participants_member_id
    ON public.participants (member_id);

CREATE INDEX idx_documents_version_source_version_id
    ON public.documents_version (source_version_id);

CREATE INDEX idx_invitations_target_user_id
    ON public.invitations (target_user_id);

-- Runtime role names are supplied by the Flyway Migration Task.
-- Example: backendRuntimeRole=a707_backend_app, yjsRuntimeRole=a707_yjs_app
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE
        public.users,
        public.teams,
        public.team_roles,
        public.members,
        public.invitations,
        public.meeting_rooms,
        public.participants,
        public.documents
    TO ${backendRuntimeRole};

GRANT USAGE, SELECT
    ON SEQUENCE
        public.users_user_id_seq,
        public.teams_team_id_seq,
        public.team_roles_team_role_id_seq,
        public.members_member_id_seq,
        public.meeting_rooms_meeting_room_id_seq,
        public.participants_participant_id_seq
    TO ${backendRuntimeRole};

GRANT SELECT, INSERT, UPDATE
    ON TABLE
        public.documents,
        public.documents_state
    TO ${yjsRuntimeRole};

GRANT SELECT, INSERT
    ON TABLE public.documents_version
    TO ${yjsRuntimeRole};
