-- Add the schedules table required by the Backend schedule feature.
-- V1 is already applied in deployed environments, so this migration is additive only.

CREATE TABLE public.schedules (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    team_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    schedule_category VARCHAR(1000) NULL,
    schedule_title VARCHAR(1000) NULL,
    schedule_description TEXT NULL,
    start_time TIMESTAMPTZ NULL,
    end_time TIMESTAMPTZ NULL,
    user_id_arr BIGINT[] NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    schedule_color VARCHAR NOT NULL DEFAULT '#566FEA',
    CONSTRAINT pk_schedules PRIMARY KEY (schedule_id),
    CONSTRAINT fk_teams_to_schedules_1
        FOREIGN KEY (team_id) REFERENCES public.teams (team_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_users_to_schedules_1
        FOREIGN KEY (creator_id) REFERENCES public.users (user_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_schedules_team_id
    ON public.schedules (team_id);

CREATE INDEX idx_schedules_user_id_arr
    ON public.schedules USING GIN (user_id_arr);

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE public.schedules
    TO ${backendRuntimeRole};

GRANT USAGE, SELECT
    ON SEQUENCE public.schedules_schedule_id_seq
    TO ${backendRuntimeRole};
