-- Add the tables that are present in the final application schema but are not
-- part of V1 or V2. Existing migrations may already be applied in deployed
-- environments, so this migration is additive and intentionally contains no
-- DROP, TRUNCATE, or data-replacement statements.

CREATE TABLE public.chats (
    chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    meeting_room_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chat TEXT NOT NULL,
    CONSTRAINT pk_chats PRIMARY KEY (chat_id),
    CONSTRAINT fk_meeting_rooms_to_chats_1
        FOREIGN KEY (meeting_room_id) REFERENCES public.meeting_rooms (meeting_room_id)
        ON DELETE RESTRICT
);

CREATE TABLE public.alarms (
    alarm_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message TEXT NOT NULL,
    alarm_category VARCHAR NOT NULL,
    alarm_property VARCHAR NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_alarms PRIMARY KEY (alarm_id),
    CONSTRAINT fk_users_to_alarms_1
        FOREIGN KEY (user_id) REFERENCES public.users (user_id)
        ON DELETE RESTRICT
);

CREATE TABLE public.minutes (
    minute_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    meeting_room_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    minute TEXT NOT NULL,
    is_checked BOOLEAN NOT NULL,
    CONSTRAINT pk_minutes PRIMARY KEY (minute_id),
    CONSTRAINT fk_meeting_rooms_to_minutes_1
        FOREIGN KEY (meeting_room_id) REFERENCES public.meeting_rooms (meeting_room_id)
        ON DELETE RESTRICT
);

CREATE TABLE public.processing_jobs (
    id UUID NOT NULL,
    meeting_id BIGINT NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'pending',
    error_message TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_processing_jobs PRIMARY KEY (id),
    CONSTRAINT fk_meeting_rooms_to_processing_jobs_1
        FOREIGN KEY (meeting_id) REFERENCES public.meeting_rooms (meeting_room_id)
        ON DELETE RESTRICT
);

CREATE TABLE public.meeting_minutes (
    meeting_id BIGINT NOT NULL,
    title VARCHAR NOT NULL,
    summary TEXT NOT NULL,
    topics JSONB NOT NULL DEFAULT '[]'::JSONB,
    decisions JSONB NOT NULL DEFAULT '[]'::JSONB,
    action_items JSONB NOT NULL DEFAULT '[]'::JSONB,
    open_issues JSONB NOT NULL DEFAULT '[]'::JSONB,
    is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_at TIMESTAMPTZ NULL,
    md_url VARCHAR NULL,
    pdf_url VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_meeting_minutes PRIMARY KEY (meeting_id),
    CONSTRAINT fk_meeting_rooms_to_meeting_minutes_1
        FOREIGN KEY (meeting_id) REFERENCES public.meeting_rooms (meeting_room_id)
        ON DELETE RESTRICT
);

CREATE TABLE public.facilitator_reports (
    meeting_id BIGINT NOT NULL,
    title VARCHAR NOT NULL,
    meeting_type VARCHAR NULL,
    overall_review TEXT NOT NULL,
    participation_comment TEXT NOT NULL,
    participation_stats JSONB NOT NULL DEFAULT '[]'::JSONB,
    quality_evaluation JSONB NOT NULL,
    strengths JSONB NOT NULL DEFAULT '[]'::JSONB,
    improvements JSONB NOT NULL DEFAULT '[]'::JSONB,
    decision_process_checks JSONB NOT NULL DEFAULT '[]'::JSONB,
    unresolved_issues_evaluation JSONB NOT NULL DEFAULT '[]'::JSONB,
    next_meeting_suggestions JSONB NOT NULL DEFAULT '[]'::JSONB,
    md_url VARCHAR NULL,
    pdf_url VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_facilitator_reports PRIMARY KEY (meeting_id),
    CONSTRAINT fk_meeting_rooms_to_facilitator_reports_1
        FOREIGN KEY (meeting_id) REFERENCES public.meeting_rooms (meeting_room_id)
        ON DELETE RESTRICT
);

CREATE TABLE public.audio_transcriptions (
    meeting_id BIGINT NOT NULL,
    transcript JSONB NOT NULL DEFAULT '[]'::JSONB,
    md_url VARCHAR NULL,
    pdf_url VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audio_transcriptions PRIMARY KEY (meeting_id),
    CONSTRAINT fk_meeting_rooms_to_audio_transcriptions_1
        FOREIGN KEY (meeting_id) REFERENCES public.meeting_rooms (meeting_room_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_chats_meeting_room_id
    ON public.chats (meeting_room_id);

CREATE INDEX idx_alarms_user_id
    ON public.alarms (user_id);

CREATE INDEX idx_minutes_meeting_room_id
    ON public.minutes (meeting_room_id);

CREATE INDEX idx_processing_jobs_meeting_id
    ON public.processing_jobs (meeting_id);

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE
        public.chats,
        public.alarms,
        public.minutes,
        public.processing_jobs
    TO ${backendRuntimeRole};

-- AI owns the report contents. Backend reads the reports and updates only the
-- application-owned confirmation and exported-file cache columns.
GRANT SELECT, UPDATE
    ON TABLE
        public.meeting_minutes,
        public.facilitator_reports,
        public.audio_transcriptions
    TO ${backendRuntimeRole};

GRANT USAGE, SELECT
    ON SEQUENCE
        public.chats_chat_id_seq,
        public.alarms_alarm_id_seq,
        public.minutes_minute_id_seq
    TO ${backendRuntimeRole};
