export function mountCommitTool(app, toast) {
const state={view:'intro',step:0,teamSection:'schedule',selected:0,darkMeeting:false};
const logo=()=>`<a class="logo" href="#" data-view="home"><span class="logo-mark"><i class="brand-yellow"></i></span>코밋툴</a>`;
const notify=text=>{toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)};

function authView(signup=false){return `<main class="auth-page"><div class="auth-logo">${logo()}</div><form class="auth-card" data-submit="auth"><h1>${signup?'회원가입':'로그인'}</h1><label class="field">이메일 주소<input type="email" placeholder="example@committool.com" required></label><label class="field"><span class="field-line">비밀번호 ${signup?'':`<button type="button">비밀번호를 잊으셨나요?</button>`}</span><div class="password-box"><input type="password" value="password" required><button type="button" data-action="eye">◉</button></div></label>${signup?`<label class="field">비밀번호 확인<div class="password-box"><input type="password" value="password" required><button type="button" data-action="eye">◉</button></div></label>`:''}<button class="primary block">${signup?'회원가입':'로그인'} →</button><div class="auth-divider"></div><p class="switch">${signup?'이미 계정이 있으신가요?':'아직 계정이 없으신가요?'} <button type="button" data-view="${signup?'login':'signup'}">${signup?'로그인':'회원가입'}</button></p></form><div class="auth-links">이용약관　 개인정보처리방침　 고객지원</div></main>`}

function introView(){return `<main class="intro-page"><header class="intro-header">${logo()}<nav><button data-view="login">로그인</button><button class="primary" data-view="signup">무료 시작하기</button></nav></header><section class="intro-hero"><span>WORK SMARTER, TOGETHER</span><h1>AI와 함께하는<br><strong>스마트한 팀 협업</strong>, 코밋툴</h1><p>문서 분석부터 스마트 스케줄링, 지능형 화상 회의까지.<br>엔터프라이즈급 AI 보안 기술로 당신의 팀이 더 본질적인 업무에 집중하도록 돕습니다.</p><div><button class="primary" data-view="signup">무료로 시작하기</button><button class="demo-btn" data-action="show-demo">◉ 데모 보기</button></div><figure><img src="/assets/메인페이지.jpg" alt="코밋툴 메인 화면 미리보기"></figure></section><section class="features"><header><span>KEY FEATURES</span><h2>팀 생산성을 극대화하는 <strong>핵심 기능</strong></h2><p>코밋툴만의 지능형 솔루션을 확인해 보세요.</p></header><div class="feature-grid"><article class="feature-card document-ai"><i>▤</i><h3>Document AI</h3><p>수천 장의 문서를 빠르게 분석하고, 핵심 요약부터 콘텐츠 기반 질문 답변까지 제공합니다.</p><img src="/assets/소개페이지.jpg" alt="Document AI 기능"></article><article class="feature-card scheduling"><i>▣</i><h3>Smart Scheduling</h3><p>팀원들의 스케줄을 분석해 최적의 미팅 시간을 제안하고 우선순위를 관리합니다.</p><img src="/assets/메인페이지.jpg" alt="스마트 일정 기능"></article><article class="feature-card meeting-feature"><div><i>◫</i><h3>지능형 화상 회의</h3><p>실시간 자동 자막, 회의록 요약과 주요 안건 트래킹까지 회의 전 과정을 AI가 보조합니다.</p><button data-view="meeting">더 알아보기 →</button></div><img src="/assets/팀 회의.jpg" alt="지능형 화상 회의"></article></div></section><section class="intro-cta"><h2>지금 바로 코밋툴과 함께<br>팀의 미래를 설계하세요.</h2><p>모든 핵심 기능을 무료로 체험해 보세요.</p><div><button data-view="signup">무료 체험 시작</button><button data-view="login">로그인</button></div></section><footer class="intro-footer">${logo()}<p>AI와 협업의 새로운 표준, 코밋툴</p><span>© 2026 CommitTool. All rights reserved.</span></footer></main>`}

const jobs=['SW 개발','기획/프로덕트','회계/금융','영업','마케팅/디자인','기타'];
const details=['Frontend','Backend','Database','DevOps','AI','Mobile'];
function onboardingView(){const titles=['직군을 선택해주세요.','세부 직무를 선택해주세요.','나이와 성별을 알려주세요.'];const labels=['직군 선택','직무 선택','나이 / 성별 선택'];return `<main class="onboarding-page"><div class="auth-logo">${logo()}</div><section class="onboarding-card"><div class="step-head"><b>STEP 0${state.step+1}/03</b><span>${labels[state.step]}</span></div><div class="progress"><i style="width:${(state.step+1)*33.34}%"></i></div><h1>${titles[state.step]}</h1>${state.step<2?`<div class="choice-grid">${(state.step?details:jobs).map((x,i)=>`<button class="${i===state.selected?'active':''}" data-choice="${i}">${x}</button>`).join('')}</div>`:`<p class="choice-label">연령대</p><div class="choice-row">${['10대','20대','30대','40대','50대','60대+'].map((x,i)=>`<button class="${i===1?'active':''}">${x}</button>`).join('')}</div><p class="choice-label">성별</p><div class="choice-row"><button>남성</button><button>여성</button></div>`}<footer class="step-footer"><button class="later" data-view="home">나중에 하기</button><button class="primary" data-action="next-step">${state.step===2?'시작':'다음'} →</button></footer></section></main>`}

const teamMenu=[['schedule','calendar','일정'],['documents','shared','공유 문서'],['minutes','minutes','회의록'],['summary','summary','AI 요약'],['feedback','star','AI 피드백'],['members','members','멤버'],['settings','settings','설정']];
function sideIcon(name){const paths={calendar:'M5 4v3m14-3v3M4 9h16M5 6h14a1 1 0 0 1 1 1v13H4V7a1 1 0 0 1 1-1Z',shared:'M6 3h8l4 4v14H6Zm8 0v5h4m-8 8 5-5 2 2-5 5H9v-3Z',minutes:'M6 3h8l4 4v14H6Zm8 0v5h4M9 12h6m-6 4h6',summary:'M4 10v10h16V8M5 11l4 4L19 5',star:'M12 2c.7 6 4 9.3 10 10-6 .7-9.3 4-10 10-.7-6-4-9.3-10-10 6-.7 9.3-4 10-10Z',members:'M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm8-1a3 3 0 1 0 0-6m-8 9c-4 0-6 2-6 5v1h12v-1c0-3-2-5-6-5Zm8 0c3.5 0 6 1.8 6 5v1h-6',settings:'M9.4 4.2 10 2h4l.6 2.2 2 .8 2-1.1 2.8 2.8-1.1 2 .8 2L22 10v4l-2.2.6-.8 2 1.1 2-2.8 2.8-2-1.1-2 .8L14 22h-4l-.6-2.2-2-.8-2 1.1-2.8-2.8 1.1-2-.8-2L2 14v-4l2.2-.6.8-2-1.1-2 2.8-2.8 2 1.1ZM12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z',lock:'M6 10h12v11H6Zm3 0V7a3 3 0 0 1 6 0v3m-3 4v3',camera:'M4 7h4l1.5-2h5L16 7h4v12H4Zm8 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z'};return `<svg class="side-icon side-icon-${name}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]}"/></svg>`}
const meetingControls=[['mic','마이크','M9 5a3 3 0 0 1 6 0v6a3 3 0 0 1-6 0Zm-3 6a6 6 0 0 0 12 0M12 17v4m-3 0h6'],['camera','카메라','M4 7h4l1.5-2h5L16 7h4v12H4Zm8 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z'],['share','공유','M5 5h14v12H5Zm7 9V8m-3 3 3-3 3 3M9 20h6'],['people','참가자','M9 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7-1a3 3 0 1 0 0-6M2 20c0-4 3-6 7-6s7 2 7 6m0-6c3 0 6 2 6 6'],['document','문서','M6 3h8l4 4v14H6Zm8 0v5h4m-8 5 4-4 2 2-4 4H9v-3Z'],['chat','채팅','M4 5h16v12H9l-5 4Zm4 5h8m-8 3h6'],['more','더보기','M12 6h.01M12 12h.01M12 18h.01']];
function meetingControl(item){return `<button class="meeting-control ${item[0]==='chat'?'active':''}" data-control="${item[0]}"><span><svg viewBox="0 0 24 24"><path d="${item[2]}"/></svg></span><small>${item[1]}</small></button>`}
function topbar(){return `<header class="topbar">${logo()}<button class="user-pill" data-view="profile"><i>김</i> 김인승</button></header>`}
function teamDock(){return `<aside class="team-dock"><strong>TEAM</strong><nav><button class="team-bubble active">A7</button><button class="team-bubble">FE</button><button class="team-bubble">PL</button><button class="team-bubble add" data-action="new-team">＋</button></nav><div class="dock-bottom"><button>?</button><button data-view="profile">⚙</button></div></aside>`}
function sideNav(active='schedule'){return `<aside class="side-nav"><small class="eyebrow">A707 TEAM</small><h2>A707</h2><p>Owner · 멤버 8명</p><nav>${teamMenu.map(x=>`<button class="${active===x[0]?'active':''}" data-team-section="${x[0]}">${sideIcon(x[1])}<span>${x[2]}</span>${x[0]==='members'?'<b>8</b>':''}</button>`).join('')}</nav><button class="back-main" data-view="home">← 메인으로</button></aside>`}
function shell(content,active='schedule',archive=false){return `<main class="app-shell">${topbar()}<div class="workspace">${teamDock()}${sideNav(active,archive)}<section class="main-area">${content}</section></div></main>`}

function calendar(){const days=['SUN','MON','TUE','WED','THU','FRI','SAT'];const cells=Array.from({length:35},(_,i)=>i-2);return `<section class="calendar"><header class="calendar-head"><h2>팀 일정</h2><div class="month-ctrl"><button>‹</button><b>2026년 7월</b><button>›</button></div></header><div class="calendar-grid">${days.map(x=>`<b>${x}</b>`).join('')}${cells.map(n=>`<div class="day ${n<1?'muted':''}">${n>0&&n<32?n:''}${n===7?'<span class="event">데일리 스크럼</span>':''}${n===14?'<span class="event">데일리 스크럼</span><span class="event green">코드 리뷰</span>':''}${n===16?'<span class="event orange">중간 발표</span>':''}</div>`).join('')}</div></section>`}
function scheduleView(){return shell(`<header class="page-heading"><div><span class="eyebrow">TEAM SCHEDULE</span><h1>A707 팀 스페이스</h1><p>진행 중인 회의와 팀 일정을 한눈에 확인하세요.</p></div><button class="outline-btn" data-action="invite">초대 링크 공유</button></header><div class="live-label"><i></i><b>진행 중인 회의</b><small>1개의 회의가 진행 중입니다.</small></div><div class="meeting-cards"><article class="live-card"><h2>BE 팀 회의　<small style="color:#15a866">LIVE</small></h2><p>백엔드 API 연동 및 배포 점검</p><footer>◷ 7월 15일 · 14:00　 ♙ 5명 참여 중 <button data-view="meeting">회의 입장 →</button></footer></article><button class="create-card" data-action="new-meeting"><i>＋</i><b>새 회의 만들기</b><span>팀원들과 바로 회의를 시작하세요.</span></button></div>${calendar()}`,'schedule')}

const members=[['JW','James Wilson','james.w@committool.io','Admin','Active','Last active 2 mins ago'],['ER','Elena Rodriguez','e.rodriguez@committool.io','Developer','Active','Last active 1h ago'],['MT','Marcus Thorne','m.thorne@committool.io','Designer','Away','Last active 4h ago'],['AK','Aisha Khan','a.khan@committool.io','Developer','Offline','Yesterday, 18:42']];
function membersView(){return shell(`<header class="page-heading"><div><span class="eyebrow">TEAM MEMBER</span><h1>팀 멤버</h1><p>팀 멤버를 초대하고 권한을 관리하세요</p></div><button class="primary" data-action="invite">＋ 멤버 초대</button></header><section class="member-table"><div class="table-tools"><span><button>☰ 조건</button> <button>☰ 정렬</button></span><input placeholder="⌕　 멤버를 찾아보세요..."></div><div class="member-row head"><span>이름</span><span>역할</span><span>상태</span><span>최근 활동</span></div>${members.map((m,i)=>`<article class="member-row"><div class="person"><i class="avatar">${m[0]}</i><span>${m[1]}<small>${m[2]}</small></span></div><span class="role">${m[3]}</span><span class="status ${m[4]==='Away'?'away':m[4]==='Offline'?'off':''}">${m[4]}</span><span>${m[5]}</span></article>`).join('')}<footer class="table-foot">Showing 4 of 8 members</footer></section>`,'members')}
const archiveData={
  documents:[['API 연동 체크리스트','BE 팀 회의','김인승 외 3명','방금 전','공동 편집'],['7월 스프린트 백로그','주간 스프린트','김인승 외 7명','18분 전','공동 편집'],['프로덕트 요구사항 v2','서비스 기획 회의','이지은 외 4명','어제','검토 중'],['배포 전 QA 체크리스트','릴리즈 점검','박서준 외 2명','7월 12일','완료']],
  minutes:[['BE 팀 회의록','BE 팀 회의','참여자 5명 · 52분','7월 15일 14:52','작성 완료'],['프론트엔드 코드 리뷰','FE 코드 리뷰','참여자 4명 · 38분','7월 14일 17:08','작성 완료'],['주간 스프린트 회의록','주간 스프린트','참여자 8명 · 61분','7월 10일 11:01','검토 필요'],['서비스 기획 정기 회의록','기획 정기 회의','참여자 6명 · 45분','7월 8일 15:45','작성 완료']],
  summary:[['백엔드 배포 점검 핵심 요약','BE 팀 회의','결정사항 3개 · 할 일 5개','1분 전','AI 생성'],['코드 리뷰 결과 요약','FE 코드 리뷰','수정사항 6개 · 할 일 3개','7월 14일','AI 생성'],['스프린트 계획 요약','주간 스프린트','결정사항 5개 · 할 일 9개','7월 10일','AI 생성'],['사용자 인터뷰 인사이트','프로덕트 인터뷰','핵심 인사이트 8개','7월 7일','AI 생성']],
  feedback:[['회의 진행 피드백','BE 팀 회의','안건 충실도 92 · 참여 균형 86','1분 전','분석 완료'],['코드 리뷰 효율 분석','FE 코드 리뷰','결론 도출 88 · 집중도 91','7월 14일','분석 완료'],['스프린트 회고 피드백','주간 스프린트','발언 균형 78 · 실행력 95','7월 10일','분석 완료'],['기획 회의 개선 제안','서비스 기획 회의','개선 제안 4개','7월 8일','분석 완료']]
};
function documentsView(section='documents'){const names={documents:'공유 문서',minutes:'회의록',summary:'AI 요약',feedback:'AI 피드백'};const descriptions={documents:'팀원과 함께 작성 중인 문서를 확인하고 편집하세요.',minutes:'회의별 발언과 결정사항이 정리된 회의록입니다.',summary:'AI가 회의의 핵심 내용과 액션 아이템을 정리했습니다.',feedback:'AI가 분석한 회의 품질과 개선 제안을 확인하세요.'};const rows=archiveData[section];return shell(`<header class="page-heading archive-heading"><div><span class="eyebrow">MEETING ARCHIVE</span><h1>${names[section]}</h1><p>${descriptions[section]}</p></div><button class="primary" data-action="new-document">＋ 새 문서</button></header><section class="archive-stats"><article><span>전체 문서</span><b>${rows.length}</b><small>이번 주 +${section==='documents'?3:2}</small></article><article><span>${section==='feedback'?'평균 참여도':'최근 업데이트'}</span><b>${section==='feedback'?'87%':'오늘'}</b><small>${section==='feedback'?'지난주 대비 +4%':'6개 변경됨'}</small></article><article><span>${section==='summary'?'완료된 액션':'팀 공유'}</span><b>${section==='summary'?'14':'8명'}</b><small>${section==='summary'?'진행 중 7개':'모든 멤버에게 공개'}</small></article></section><section class="archive-panel"><div class="archive-tools"><div class="filter-tabs"><button class="active">전체</button><button>최근 열어본</button><button>내 문서</button></div><label>⌕<input placeholder="${names[section]} 검색"></label><select><option>최근 수정 순</option><option>이름 순</option></select></div><div class="archive-list">${rows.map((r,i)=>`<article class="archive-row"><i class="archive-icon ${section}">${section==='summary'?'AI':section==='feedback'?'✦':'▤'}</i><div class="archive-title"><b>${r[0]}</b><span>${r[1]}</span></div><div><small>${section==='documents'?'편집자':'회의 정보'}</small><b>${r[2]}</b></div><div><small>업데이트</small><b>${r[3]}</b></div><em>${r[4]}</em><button data-action="open-document">열기 →</button></article>`).join('')}</div><footer class="archive-footer"><span>총 ${rows.length}개의 항목</span><div><button disabled>‹</button><button class="active">1</button><button>›</button></div></footer></section>`,section,true)}

function teamSettingsView(){return shell(`<header class="page-heading"><div><span class="eyebrow">TEAM SETTINGS</span><h1>팀 스페이스 설정</h1><p>팀 정보, 접근 권한과 알림 정책을 관리하세요.</p></div><button class="primary" data-action="save-team">변경사항 저장</button></header><div class="team-settings-grid"><section class="settings-card"><header><i>A7</i><div><h2>기본 정보</h2><p>팀 멤버에게 표시되는 정보입니다.</p></div></header><label class="field">팀 스페이스 이름<input value="A707"></label><label class="field">팀 설명<textarea>화상회의 협업 플랫폼을 함께 만드는 프로젝트 팀입니다.</textarea></label><label class="field">팀 대표 색상<select><option>Commit Blue</option><option>Emerald</option><option>Orange</option></select></label></section><section class="settings-card"><header><i>♙</i><div><h2>접근 및 권한</h2><p>새 멤버의 기본 접근 수준을 설정합니다.</p></div></header><div class="setting-toggle"><span><b>초대 링크 활성화</b><small>링크를 가진 사용자가 가입할 수 있습니다.</small></span><button class="switch-on" data-action="toggle-switch"><i></i></button></div><div class="setting-toggle"><span><b>Owner 승인 필요</b><small>새 멤버 가입 전 승인을 요청합니다.</small></span><button data-action="toggle-switch"><i></i></button></div><label class="field">신규 멤버 기본 역할<select><option>Member</option><option>Guest</option><option>Admin</option></select></label></section><section class="settings-card wide"><header><i>♢</i><div><h2>알림 설정</h2><p>팀 전체에 적용되는 기본 알림입니다.</p></div></header><div class="notification-grid"><label><input type="checkbox" checked> 회의 시작 10분 전 알림</label><label><input type="checkbox" checked> 새 문서 및 댓글 알림</label><label><input type="checkbox" checked> AI 요약 생성 완료 알림</label><label><input type="checkbox"> 주간 활동 리포트</label></div></section><section class="settings-card danger wide"><header><i>!</i><div><h2>위험 영역</h2><p>이 작업은 되돌릴 수 없으니 주의하세요.</p></div><button class="danger-btn">팀 스페이스 삭제</button></header></section></div>`,'settings')}

function homeView(){return shell(`<header class="page-heading"><div><span class="eyebrow">MY WORKSPACES</span><h1>나의 일정</h1><p>참여 중인 모든 팀의 회의를 한눈에 확인하세요.</p></div></header><div class="live-label"><i></i><b>회의 바로가기</b><small>1개의 회의가 진행 중입니다.</small></div><article class="live-card"><h2>BE 팀 회의　<small style="color:#15a866">LIVE</small></h2><p>백엔드 API 연동 및 배포 점검</p><footer>◷ 7월 15일 · 14:00　 ♙ 5명 참여 중 <button data-view="meeting">회의 입장 →</button></footer></article>${calendar()}`,'schedule')}

function settingsSide(active){return `<aside class="side-nav settings-nav"><div class="search-dark">⌕　기능 검색</div><small class="settings-label">설정</small><nav class="settings-menu"><button class="${active==='profile'?'active':''}" data-view="profile">${sideIcon('members')}<span>프로필 변경</span></button><button class="${active==='password'?'active':''}" data-view="password">${sideIcon('lock')}<span>비밀번호 변경</span></button></nav><button class="back-main" data-view="home">← 이전으로 가기</button></aside>`}
function settingsShell(content,active){return `<main class="app-shell">${topbar()}<div class="workspace settings-shell">${settingsSide(active)}<section class="settings-content">${content}</section></div></main>`}
function profileView(){return settingsShell(`<form class="profile-settings" data-submit="save"><header class="account-heading"><span>ACCOUNT SETTINGS</span><h1>프로필 설정</h1><p>내 정보를 최신 상태로 유지하고 팀원들에게 나를 소개해 보세요.</p></header><div class="profile-settings-body"><aside class="photo-card"><div class="photo-circle">${sideIcon('camera')}<button type="button">＋</button></div><b>프로필 사진</b><small>권장 크기 400 × 400px<br>JPG, PNG · 최대 5MB</small><button type="button" class="upload-photo">사진 업로드</button><p>✓ 얼굴이 잘 보이는 사진을 권장해요.</p></aside><section class="profile-fields"><div class="form-section-title"><b>기본 정보</b><small>서비스에서 표시되는 정보를 입력해 주세요.</small></div><label class="field">닉네임<div class="input-with-meta"><span>♙</span><input value="김인승" maxlength="10"><small>3/10</small></div></label><label class="field">전화번호<input value="010-1234-5678"></label><div class="form-section-title role-title"><b>직무 및 프로필</b><small>맞춤형 팀 경험을 위해 직무 정보를 선택해 주세요.</small></div><div class="profile-grid"><fieldset><legend>성별</legend><label class="radio-card active"><input type="radio" name="profile-gender" checked> 남</label><label class="radio-card"><input type="radio" name="profile-gender"> 여</label></fieldset><label class="field">연령대<select><option>20 - 30</option><option>30 - 40</option></select></label><label class="field">직군<select><option>소프트웨어 개발</option><option>기획/프로덕트</option></select></label><label class="field">세부 직무<select><option>Frontend Developer</option><option>Backend Developer</option></select></label></div><button class="primary profile-submit">저장</button></section></div></form>`,'profile')}
function passwordView(){return settingsShell(`<div class="password-layout password-settings"><form class="password-card" data-submit="save"><h1>비밀번호 변경</h1><label class="field">현재 비밀번호<div class="password-box"><input type="password" value="password"><button type="button" data-action="eye">◉</button></div></label><hr><label class="field">새로운 비밀번호<div class="password-box"><input type="password" value="password"><button type="button" data-action="eye">◉</button></div></label><div class="strength-label"><b>비밀번호 강도</b><span>약함</span></div><div class="strength-bar"><i></i></div><label class="field">새로운 비밀번호 확인<div class="password-box"><input type="password" value="password"><button type="button" data-action="eye">◉</button></div></label><div class="password-actions"><button class="primary">비밀번호 변경 →</button><button type="button">취소</button></div></form><aside><section class="requirements"><h2>보안 요구사항</h2><article><i>✓</i><div><b>최소 12자 이상</b><p>긴 비밀번호일수록 무차별 대입 공격에 더 안전합니다.</p></div></article><article><i>✓</i><div><b>복잡성</b><p>문자(A-z), 숫자(0-9), 특수문자(!@#)를 조합하세요.</p></div></article><article><i>✓</i><div><b>반복 피하기</b><p>이메일 주소 일부나 단순한 연속 문자를 사용하지 마세요.</p></div></article></section></aside></div>`,'password')}

function meetingView(){return `<main class="meeting-room ${state.darkMeeting?'dark':''}"><header class="meeting-top"><h1>🔴　주간 기획 회의 (LIVE)</h1><span>◉ ◉ <b>+12</b>　? 도움말</span></header><div class="meeting-content"><section class="video-column"><div class="video-grid"><article class="video-tile"><div class="video-person">나</div><label>🎙 나 (홍길동)</label></article><article class="video-tile"><div class="video-person">이지은</div><label>🎙 이지은 팀장</label></article><article class="video-tile"><div class="video-person">KM</div><label>🔇 김민수 매니저</label></article><article class="video-tile"><div class="video-person">박서준</div><label>🎙 박서준</label></article></div><footer class="controls"><span class="meeting-agenda">오후 2:30　| 주간 기획 회의</span><div class="control-items">${meetingControls.map(meetingControl).join('')}</div><i class="control-divider"></i><button class="hangup" data-view="home" aria-label="통화 종료"><svg viewBox="0 0 24 24"><path d="M5 15c4-4 10-4 14 0l-2 3-3-2v-3h-4v3l-3 2Z"/></svg></button></footer></section><aside class="chat-panel"><nav class="chat-tabs"><button class="active">채팅</button><button>다이렉트</button></nav><section class="messages"><article><b>이지은 팀장　<small>2:15</small></b><p>오늘 회의 자료 모두 확인하셨나요?</p></article><article class="me"><b>나　<small>2:16</small></b><p>네, 3페이지 수정사항 반영해서 업로드했습니다.</p></article><article><b>김민수 매니저　<small>2:18</small></b><p>확인했습니다. 감사합니다!</p></article></section><form class="chat-input" data-submit="chat"><input placeholder="메시지를 입력하세요..."><button>▷</button></form></aside></div></main>`}

function modal(type){if(type==='team')return `<div class="modal-backdrop"><form class="modal" data-submit="modal"><button class="close" type="button" data-action="close">×</button><small style="color:#4285ef">NEW TEAM SPACE</small><h2>새 팀 스페이스</h2><label class="field">팀 이름<input required></label><label class="field">설명<textarea></textarea></label><div class="colors"><span style="margin-right:auto"><b>팀 색상</b><br><small>팀 아이콘과 포인트 색상에 사용됩니다.</small></span>${['red','#20c266','#ff6811','#5888e8','white'].map(c=>`<button type="button" style="background:${c};border:${c==='white'?'1px solid #111':'0'}"></button>`).join('')}</div><button class="primary block">팀 스페이스 만들기</button></form></div>`;if(type==='meeting')return `<div class="modal-backdrop"><form class="modal" data-submit="modal"><button class="close" type="button" data-action="close">×</button><small style="color:#4285ef">NEW MEETING</small><h2>회의 생성하기</h2><label class="field">회의 이름<input required></label><label class="field">담당 팀<select><option>A707</option><option>Frontend</option></select></label><div style="height:105px"></div><button class="primary block">회의 만들기</button></form></div>`;return `<div class="modal-backdrop"><section class="modal invite-modal"><button class="close" data-action="close">×</button><h2>멤버 초대 및 공유</h2><p>프로젝트 팀원을 초대하세요.</p><div class="invite-row"><input placeholder="email@example.com"><select><option>편집 가능</option></select><button class="primary">초대 발송 →</button></div><div class="invite-list"><b>현재 멤버 4</b>${['김지수 (나)','박민호','이지은','Robert Ford'].map((x,i)=>`<article><i class="avatar">${i?'M':'김'}</i><span>${x}<br><small>member@committool.com</small></span><em>${i?'MEMBER':'OWNER'}</em></article>`).join('')}</div><button class="outline-btn block">▣ 링크 복사</button></section></div>`}

const views={intro:introView,login:()=>authView(false),signup:()=>authView(true),onboarding:onboardingView,home:homeView,schedule:scheduleView,members:membersView,documents:()=>documentsView('documents'),minutes:()=>documentsView('minutes'),summary:()=>documentsView('summary'),feedback:()=>documentsView('feedback'),settings:teamSettingsView,profile:profileView,password:passwordView,meeting:meetingView};
function render(view=state.view){state.view=view;app.innerHTML=views[view]();window.scrollTo(0,0)}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){e.preventDefault();render(view.dataset.view);return}const section=e.target.closest('[data-team-section]');if(section){render(section.dataset.teamSection);return}const choice=e.target.closest('[data-choice]');if(choice){state.selected=Number(choice.dataset.choice);render();return}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='show-demo')render('home');if(action==='next-step'){if(state.step<2){state.step++;state.selected=0;render('onboarding')}else render('home')}if(action==='eye'){const input=e.target.closest('.password-box').querySelector('input');input.type=input.type==='password'?'text':'password'}if(action==='new-team')document.body.insertAdjacentHTML('beforeend',modal('team'));if(action==='new-meeting')document.body.insertAdjacentHTML('beforeend',modal('meeting'));if(action==='new-document')notify('새 문서 작성 화면을 준비했습니다.');if(action==='open-document')notify('문서를 열었습니다.');if(action==='save-team')notify('팀 설정을 저장했습니다.');if(action==='toggle-switch')e.target.closest('button').classList.toggle('switch-on');if(action==='invite')document.body.insertAdjacentHTML('beforeend',modal('invite'));if(action==='close')e.target.closest('.modal-backdrop').remove();if(e.target.closest('[data-control]'))e.target.closest('[data-control]').classList.toggle('primary')});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.dataset.submit==='auth'){state.step=0;render('onboarding')}if(e.target.dataset.submit==='save')notify('변경사항을 저장했습니다.');if(e.target.dataset.submit==='modal'){e.target.closest('.modal-backdrop').remove();notify('성공적으로 만들었습니다.')}if(e.target.dataset.submit==='chat'){const input=e.target.querySelector('input');if(input.value.trim()){document.querySelector('.messages').insertAdjacentHTML('beforeend',`<article class="me"><b>나　<small>방금</small></b><p>${input.value.replace(/[<>]/g,'')}</p></article>`);input.value=''}}});
render();
return () => {};
}
